name: syncserve
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter   
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0    
  zod_validation: ^1.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
  generate: true  
