name: syncserve
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0    
  mailer: ^6.4.1
  zod_validation: ^1.0.5
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  signature: ^6.3.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - .env
  generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FF6455"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
